In [368]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [331]:
df = pd.read_csv("Auto_fraud.csv")
df.head(7)

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,WitnessPresent,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,3 years,26 to 30,No,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,6 years,31 to 35,Yes,No,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,7 years,41 to 50,No,No,External,none,no change,1 vehicle,1994,Collision
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,more than 7,51 to 65,Yes,No,External,more than 5,no change,1 vehicle,1994,Liability
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,5 years,31 to 35,No,No,External,none,no change,1 vehicle,1994,Collision
5,Oct,4,Friday,Honda,Urban,Wednesday,Nov,1,Male,Single,...,5 years,21 to 25,No,No,External,3 to 5,no change,1 vehicle,1994,Collision
6,Feb,1,Saturday,Honda,Urban,Monday,Feb,3,Male,Married,...,7 years,36 to 40,No,No,External,1 to 2,no change,1 vehicle,1994,Collision

In [332]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15420 entries, 0 to 15419
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Month                 15420 non-null  object
 1   WeekOfMonth           15420 non-null  int64
 2   DayOfWeek             15420 non-null  object
 3   Make                  15420 non-null  object
 4   AccidentArea          15420 non-null  object
 5   DayOfWeekClaimed      15420 non-null  object
 6   MonthClaimed          15420 non-null  object
 7   WeekOfMonthClaimed    15420 non-null  int64
 8   Sex                   15390 non-null  object
 9   MaritalStatus         15391 non-null  object
 10  Age                   15394 non-null  float64
 11  Fault                 15420 non-null  object
 12  PolicyType            15420 non-null  object
 13  VehicleCategory       15420 non-null  object
 14  VehiclePrice          15420 non-null  object
 15  FraudFound_P          15420 non-null  int64
 16  PolicyNumber          15420 non-null  int64
 17  RepNumber             15420 non-null  int64
 18  Deductible            15420 non-null  int64
 19  DriverRating          15420 non-null  int64
 20  Days_Policy_Accident  15420 non-null  object
 21  Days_Policy_Claim     15420 non-null  object
 22  PastNumberOfClaims    15420 non-null  object
 23  AgeOfVehicle          15420 non-null  object
 24  AgeOfPolicyHolder     15420 non-null  object
 25  PoliceReportFiled     15420 non-null  object
 26  WitnessPresent        15407 non-null  object
 27  AgentType             15420 non-null  object
 28  NumberOfSuppliments   15420 non-null  object
 29  AddressChange_Claim   15420 non-null  object
 30  NumberOfCars          15420 non-null  object
 31  Year                  15420 non-null  int64
 32  BasePolicy            15420 non-null  object
dtypes: float64(1), int64(8), object(24)
memory usage: 3.9+ MB

In [333]:
df.shape

(15420, 33)

In [334]:
df.columns

Index(['Month', 'WeekOfMonth', 'DayOfWeek', 'Make', 'AccidentArea',
       'DayOfWeekClaimed', 'MonthClaimed', 'WeekOfMonthClaimed', 'Sex',
       'MaritalStatus', 'Age', 'Fault', 'PolicyType', 'VehicleCategory',
       'VehiclePrice', 'FraudFound_P', 'PolicyNumber', 'RepNumber',
       'Deductible', 'DriverRating', 'Days_Policy_Accident',
       'Days_Policy_Claim', 'PastNumberOfClaims', 'AgeOfVehicle',
       'AgeOfPolicyHolder', 'PoliceReportFiled', 'WitnessPresent', 'AgentType',
       'NumberOfSuppliments', 'AddressChange_Claim', 'NumberOfCars', 'Year',
       'BasePolicy'],
      dtype='object')

In [335]:
df.isnull().sum()

Month                    0
WeekOfMonth              0
DayOfWeek                0
Make                     0
AccidentArea             0
DayOfWeekClaimed         0
MonthClaimed             0
WeekOfMonthClaimed       0
Sex                     30
MaritalStatus           29
Age                     26
Fault                    0
PolicyType               0
VehicleCategory          0
VehiclePrice             0
FraudFound_P             0
PolicyNumber             0
RepNumber                0
Deductible               0
DriverRating             0
Days_Policy_Accident     0
Days_Policy_Claim        0
PastNumberOfClaims       0
AgeOfVehicle             0
AgeOfPolicyHolder        0
PoliceReportFiled        0
WitnessPresent          13
AgentType                0
NumberOfSuppliments      0
AddressChange_Claim      0
NumberOfCars             0
Year                     0
BasePolicy               0
dtype: int64

In [336]:
#filling missing value with mean of Age: 
mean=df['Age'].mean()
df['Age'].fillna( mean , inplace=True)

#filling missing value with mode of Sex:
df['Sex'].replace('Male'==1, 'Female'==0)
mode = df['Sex'].mode()[0]  # Calculate the mode of the 'Sex' column
df['Sex'].fillna(mode, inplace=True)

#Changing the DType of Age:
df['Age'] = df['Age'].astype(object)
df['FraudFound_P'] = df['FraudFound_P'].astype(object)

In [337]:
# Drop the 'Witness' column from the DataFrame
df.drop(columns=['WitnessPresent'], inplace=True)


# Fill missing values in the 'MaritalStatus' column with the mode
mode_marital_status = df['MaritalStatus'].mode()[0]
df['MaritalStatus'].fillna(mode_marital_status, inplace=True)

In [338]:
df

,Month,WeekOfMonth,DayOfWeek,Make,AccidentArea,DayOfWeekClaimed,MonthClaimed,WeekOfMonthClaimed,Sex,MaritalStatus,...,PastNumberOfClaims,AgeOfVehicle,AgeOfPolicyHolder,PoliceReportFiled,AgentType,NumberOfSuppliments,AddressChange_Claim,NumberOfCars,Year,BasePolicy
0,Dec,5,Wednesday,Honda,Urban,Tuesday,Jan,1,Female,Single,...,none,3 years,26 to 30,No,External,none,1 year,3 to 4,1994,Liability
1,Jan,3,Wednesday,Honda,Urban,Monday,Jan,4,Male,Single,...,none,6 years,31 to 35,Yes,External,none,no change,1 vehicle,1994,Collision
2,Oct,5,Friday,Honda,Urban,Thursday,Nov,2,Male,Married,...,1,7 years,41 to 50,No,External,none,no change,1 vehicle,1994,Collision
3,Jun,2,Saturday,Toyota,Rural,Friday,Jul,1,Male,Married,...,1,more than 7,51 to 65,Yes,External,more than 5,no change,1 vehicle,1994,Liability
4,Jan,5,Monday,Honda,Urban,Tuesday,Feb,2,Female,Single,...,none,5 years,31 to 35,No,External,none,no change,1 vehicle,1994,Collision
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15415,Nov,4,Friday,Toyota,Urban,Tuesday,Nov,5,Male,Married,...,2 to 4,6 years,31 to 35,No,External,none,no change,1 vehicle,1996,Collision
15416,Nov,5,Thursday,Pontiac,Urban,Friday,Dec,1,Male,Married,...,more than 4,6 years,31 to 35,No,External,more than 5,no change,3 to 4,1996,Liability
15417,Nov,5,Thursday,Toyota,Rural,Friday,Dec,1,Male,Single,...,more than 4,5 years,26 to 30,No,External,1 to 2,no change,1 vehicle,1996,Collision
15418,Dec,1,Monday,Toyota,Urban,Thursday,Dec,2,Female,Married,...,none,2 years,31 to 35,No,External,more than 5,no change,1 vehicle,1996,All Perils
15419,Dec,2,Wednesday,Toyota,Urban,Thursday,Dec,3,Male,Single,...,none,5 years,26 to 30,No,External,1 to 2,no change,1 vehicle,1996,Collision

In [339]:
df.isnull().sum()

Month                   0
WeekOfMonth             0
DayOfWeek               0
Make                    0
AccidentArea            0
DayOfWeekClaimed        0
MonthClaimed            0
WeekOfMonthClaimed      0
Sex                     0
MaritalStatus           0
Age                     0
Fault                   0
PolicyType              0
VehicleCategory         0
VehiclePrice            0
FraudFound_P            0
PolicyNumber            0
RepNumber               0
Deductible              0
DriverRating            0
Days_Policy_Accident    0
Days_Policy_Claim       0
PastNumberOfClaims      0
AgeOfVehicle            0
AgeOfPolicyHolder       0
PoliceReportFiled       0
AgentType               0
NumberOfSuppliments     0
AddressChange_Claim     0
NumberOfCars            0
Year                    0
BasePolicy              0
dtype: int64

In [340]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
import pandas as pd

# 1. Convert target to integer (if it's not already)
df['FraudFound_P'] = df['FraudFound_P'].astype(int)  # Force conversion to integer

# 2. Prepare data (convert categorical to dummies)
X = pd.get_dummies(df.drop('FraudFound_P', axis=1), drop_first=True)
y = df['FraudFound_P']

# 3. Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 4. Apply SMOTE
try:
    sm = SMOTE(random_state=42)
    X_resampled, y_resampled = sm.fit_resample(X_train, y_train)
    print("Class counts after SMOTE:", pd.Series(y_resampled).value_counts())
except Exception as e:
    print("Error:", e)
    print("\nDebugging info:")
    print("y_train unique values:", y_train.unique())
    print("y_train types:", y_train.apply(type).unique())

Class counts after SMOTE: FraudFound_P
0    10141
1    10141
Name: count, dtype: int64

In [341]:
x=df2.drop('FraudFound_P',axis='columns')
y=df2.FraudFound_P

In [365]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=20,test_size=0.2)
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)
model.score(x_train,y_train)

0.8235192540148506

In [366]:
model.score(x_test,y_test)

0.8102555248618785

In [367]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Calculate metrics specifically for fraud cases (class=1)
y_pred = model.predict(x_test)
precision = precision_score(y_test, y_pred, pos_label=1)
recall = recall_score(y_test, y_pred, pos_label=1)
f1 = f1_score(y_test, y_pred, pos_label=1)

print(f"Fraud Detection Metrics (Class 1):")
print(f"Precision: {precision:.4f}")  # Accuracy when predicting fraud
print(f"Recall:    {recall:.4f}")     # Ability to catch actual fraud
print(f"F1-Score:  {f1:.4f}")        # Balance between precision/recall

Fraud Detection Metrics (Class 1):
Precision: 0.7714
Recall:    0.8881
F1-Score:  0.8256

In [364]:
def fraud_detection_interface():
    print("\n" + "="*50)
    print("🔍 FRAUD-DETECTION SYSTEM TEST INTERFACE")
    print("="*50)
    
    try:
        # Collect key features from the user
        print("\nEnter claim details:")
        age = float(input("• Policy Holder Age: "))
        days_policy_accident = int(input("• Days Since Policy Start: "))
        past_claims = int(input("• Past Number of Claims: "))
        num_supplements = int(input("• Number of Supplements: "))
        police_report = input("• Police Report Filed? (yes/no): ").lower().strip()
        accident_area = input("• Accident Area (urban/rural): ").lower().strip()
        vehicle_price = input("• Vehicle Price (high/medium/low): ").lower().strip()
        
        # Create a dictionary with default values for all features in x_train.
        input_dict = {}
        for col in x_train.columns:
            input_dict[col] = 0  
        
        input_dict['Age'] = age
        input_dict['Days_Policy_Accident'] = days_policy_accident
        input_dict['PastNumberOfClaims'] = past_claims
        input_dict['NumberOfSuppliments'] = num_supplements
        
    
        input_dict['PoliceReportFiled_yes'] = 1 if police_report == 'yes' else 0
        input_dict['PoliceReportFiled_no'] = 1 if police_report == 'no' else 0
        
        input_dict['AccidentArea'] = 1 if accident_area == 'urban' else 0
        
        input_dict['VehiclePrice_high'] = 1 if vehicle_price == 'high' else 0
        input_dict['VehiclePrice_medium'] = 1 if vehicle_price == 'medium' else 0
        input_dict['VehiclePrice_low'] = 1 if vehicle_price == 'low' else 0
        
        test_input_df = pd.DataFrame([input_dict])
        test_input_df = test_input_df[x_train.columns]
        
        prob_fraud = model.predict_proba(test_input_df)[0][1]
        prediction = "FRAUD" if prob_fraud > 0.5 else "LEGITIMATE"
        
        print("\n" + "="*50)
        print("PREDICTION RESULT:")
        print("Status:", prediction)
        print("Confidence (fraud probability):", f"{prob_fraud:.1%}")
        print("="*50)
        
    except ValueError:
        print("\nError: Please enter valid numbers where required")
    except Exception as e:
        print(f"\n An error occurred: {str(e)}")

fraud_detection_interface()

==================================================
🔍 FRAUD-DETECTION SYSTEM TEST INTERFACE
==================================================

Enter claim details:

• Policy Holder Age:  qq

Error: Please enter valid numbers where required